/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE IF NOT EXISTS `skinvendoritems` (
  `SkinVendorItemID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` text NOT NULL,
  `ModelID` int(11) NOT NULL DEFAULT 0,
  `ItemType` int(11) NOT NULL DEFAULT 0,
  `PlayerRealmRank` int(11) NOT NULL DEFAULT 0,
  `AccountRealmRank` int(11) NOT NULL DEFAULT 0,
  `Drake` int(11) NOT NULL DEFAULT 0,
  `Orbs` int(11) NOT NULL DEFAULT 0,
  `EpicBossKills` int(11) NOT NULL DEFAULT 0,
  `MasteredCrafts` int(11) NOT NULL DEFAULT 0,
  `Realm` int(11) NOT NULL DEFAULT 0,
  `CharacterClass` int(11) NOT NULL DEFAULT 0,
  `ObjectType` int(11) NOT NULL DEFAULT 0,
  `DamageType` int(11) NOT NULL DEFAULT 0,
  `Price` int(11) NOT NULL DEFAULT 0,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`SkinVendorItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*!40000 ALTER TABLE `skinvendoritems` DISABLE KEYS */;
/*!40000 ALTER TABLE `skinvendoritems` ENABLE KEYS */;

